[sentimentClientConfig]
clientUrl = "CLIENT_URL"
refreshUrl = "OAUTH2_REFRESH_URL"
refreshToken = "OAUTH2_REFRESH_TOKEN"
clientId = "OAUTH2_CLIENT_ID"
clientSecret = "OAUTH2_CLIENT_SECRET"

[dbConfig]
host = "HOST"
user = "USER"
password = "PASSWORD"
database = "DATABASE"
port = 0