version: '2.14.0'

services:
  mysql:
    image: 'mysql:8-oracle'
    ports:
      - '3306:3306'
    network_mode: "host"
    environment:
      - MYSQL_ROOT_PASSWORD=dummypassword
      - MYSQL_DATABASE=forum_database
      - MYSQL_USER=forum_user
      - MYSQL_PASSWORD=dummypassword
    healthcheck:
        test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
        timeout: 20s
        retries: 10
    volumes:
      - "./db-setup/init.sql:/docker-entrypoint-initdb.d/1.sql"

  sts:
    image: ldclakmal/ballerina-sts:latest
    ports:
      - "9445:9445"
    network_mode: "host"
    platform: linux/amd64

  nats:
    image: nats:latest
    ports:
      - "4222:4222"
    network_mode: "host"

  sentiment-api:
    image: wso2/sentiment-api:0.1.0
    ports:
      - "9000:9000"
    network_mode: "host"
    platform: linux/amd64
    depends_on:
      sts:
        condition: service_started

  nats-mail-notifier:
    image: wso2/nats-mail-notifier:0.1.0
    ports:
      - "4222:4222"
    network_mode: "host"
    platform: linux/amd64
    depends_on:
      nats:
        condition: service_started

  bal-forum:
    image: wso2/bal-forum:0.1.0
    ports:
      - "4000:4000"
    network_mode: "host"
    platform: linux/amd64
    depends_on:
      sentiment-api:
        condition: service_started
      sts:
        condition: service_started
      mysql:
        condition: service_healthy
      nats-mail-notifier:
        condition: service_started
