version: '2.14.0'

services:
  mysql:
    image: 'mysql:8-oracle'
    ports:
      - '3306:3306'
    network_mode: "host"
    environment:
      - MYSQL_ROOT_PASSWORD=dummypassword
      - MYSQL_DATABASE=forum_database
      - MYSQL_USER=forum_user
      - MYSQL_PASSWORD=dummypassword
    healthcheck:
        test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
        timeout: 20s
        retries: 10
    volumes:
      - "./db-setup/init.sql:/docker-entrypoint-initdb.d/1.sql"

  nats:
    image: nats:latest
    command: "-c /etc/nats/server.conf -V"
    ports:
      - "4222:4222"
    network_mode: "host"
    volumes:
      - "./nats-config:/etc/nats/"

  sts:
    image: ldclakmal/ballerina-sts:latest
    ports:
      - "9445:9445"
    network_mode: "host"

  jaeger:
    image: 'jaegertracing/opentelemetry-all-in-one'
    ports:
      - '13133:13133'
      - '16686:16686'
      - '55680:55680'
      - '4317:4317'
    network_mode: "host"
